### ISSUE TITLE
JSONObject["czesci-wykonawcy"] not found

### ISSUE THREAD

**Issue by KrzysztofMadejski** [petabyte-research/redflags#22]
Takie wyjątki lecą na stderr. Jeżeli są one odpowiednio wcześnie wyłapywane i dobrze obsługiwane to nie powinny być wypisywane na stderr moim zdaniem.

```
org.json.JSONException: JSONObject["czesci-wykonawcy"] not found.
        at org.json.JSONObject.get(JSONObject.java:498)
        at org.json.JSONObject.getJSONObject(JSONObject.java:592)
        at hu.petabyte.redflags.engine.epforgpl.EPFMapper.getContractibnAuthority(EPFMapper.java:237)
        at hu.petabyte.redflags.engine.epforgpl.EPFMapper.getNotice(EPFMapper.java:57)
        at hu.petabyte.redflags.engine.gear.parser.pl.ProcurementParser.processImpl(ProcurementParser.java:42)
        at hu.petabyte.redflags.engine.gear.AbstractGear.process(AbstractGear.java:38)
        at hu.petabyte.redflags.engine.gear.GearTrain.call(GearTrain.java:57)
        at hu.petabyte.redflags.engine.gear.GearTrain.call(GearTrain.java:33)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
org.json.JSONException: JSONObject[""] not found.
        at org.json.JSONObject.get(JSONObject.java:498)
        at org.json.JSONObject.getJSONObject(JSONObject.java:592)
        at hu.petabyte.redflags.engine.epforgpl.EPFMapper.getContractibnAuthority(EPFMapper.java:238)
        at hu.petabyte.redflags.engine.epforgpl.EPFMapper.getNotice(EPFMapper.java:57)
        at hu.petabyte.redflags.engine.gear.parser.pl.ProcurementParser.processImpl(ProcurementParser.java:42)
        at hu.petabyte.redflags.engine.gear.AbstractGear.process(AbstractGear.java:38)
        at hu.petabyte.redflags.engine.gear.GearTrain.call(GearTrain.java:57)
        at hu.petabyte.redflags.engine.gear.GearTrain.call(GearTrain.java:33)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by KrzysztofMadejski** [comment]
To powinno byc na poziomie `debug` logowane lub trace

**Comment by dzierzy** [comment]
fixed
