### ISSUE TITLE
Graphs: wrong SQL statement

### ISSUE THREAD

**Issue by KrzysztofMadejski** [petabyte-research/redflags#23]
On http://tcee-redflags.epf.p5.tiktalik.io:8080/
- [x] second graph/statistic doesn't appear
- [ ] third graph has no categories, only "Series 1", "Series 2"

**Comment by KrzysztofMadejski** [comment]
@dzierzy będziesz mógł spojrzeć na to?

In the chrome console I'm getting error: `GET http://pl.redflags.transparencee.org/chart/flaggedNotices 500 (Internal Server Error)`

**Comment by KrzysztofMadejski** [comment]
I've got the error, seems like a problem with orginal query (CC: @juzraai )

```
2016-10-11 21:13:13.669 ERROR 8514 --- [io-8080-exec-10] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [select distinct concat(year(date), ' - ', quarter(date)) from rfwl_notices order by date]; SQL state [HY000]; error code [3065]; Expression #1 of ORDER BY clause is not in SELECT list, references column 'rf.rfwl_notices.date' which is not in SELECT list; this is incompatible with DISTINCT; nested exception is java.sql.SQLException: Expression #1 of ORDER BY clause is not in SELECT list, references column 'rf.rfwl_notices.date' which is not in SELECT list; this is incompatible with DISTINCT] with root cause

java.sql.SQLException: Expression #1 of ORDER BY clause is not in SELECT list, references column 'rf.rfwl_notices.date' which is not in SELECT list; this is incompatible with DISTINCT
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:963) ~[mysql-connector-java-5.1.39.jar!/:5.1.39]
        ...
        at org.springframework.jdbc.core.JdbcTemplate.queryForList(JdbcTemplate.java:501) ~[spring-jdbc-4.2.7.RELEASE.jar!/:4.2.7.RELEASE]
        at hu.petabyte.redflags.web.svc.ChartSvc.quarters(ChartSvc.java:134) ~[redflags-web-1.0.1496.jar!/:${app.version}]
        at hu.petabyte.redflags.web.ctrl.ChartCtrl.flaggedNotices(ChartCtrl.java:41) ~[redflags-web-1.0.1496.jar!/:${app.version}]
```

**Comment by juzraai** [comment]
Okay, so `ChartSvc.quarters()` method runs this simple query:

``` sql
select distinct concat(year(date), ' - ', quarter(date)) from rfwl_notices order by date
```

It works perfectly fine for me, but I've just found this: https://github.com/Elgg/Elgg/issues/8121 

It seems MySQL 5.7 introduced new constraints which can be turned off by changing the MySQL server configuration. Do you use MySQL 5.7? Can you try out this solution?

**Comment by KrzysztofMadejski** [comment]
It helped, thanks!

I've checked the current mode `select @@GLOBAL.sql_mode;`
and set it without the `ONLY_FULL_GROUP_BY` in `my.cnf`.

**Comment by KrzysztofMadejski** [comment]
The third graph still don't return any data. We need to check which data we are missing in the mapping.

**Comment by dzierzy** [comment]
chart no 2 is working now. for chart no 3 we have no data for value of contract.

**Comment by KrzysztofMadejski** [comment]
Value of contract is in the ""zamowienia_publiczne.wartosc_cena" MPAPI field. But the aggregation script suffers from hardcoded amount #30.
