### ISSUE TITLE
Error in uploading data to SQL db

### ISSUE THREAD

**Issue by KrzysztofMadejski** [petabyte-research/redflags#47]
```
2016-10-24 21:18:36,778 [DEBUG] [     rf-engine-0] h.p.r.engine.gear.export.MySQLExporter   > Pushing CSV into MySQL: te_relationdescriptor_20161024
2016-10-24 21:18:38,543 [DEBUG] [     rf-engine-0] h.p.r.engine.gear.export.MySQLExporter   > Pushing CSV into MySQL: te_objofthecontract_20161024
2016-10-24 21:18:40,389 [DEBUG] [     rf-engine-0] h.p.r.engine.gear.export.MySQLExporter   > Pushing CSV into MySQL: te_datatype_20161024
2016-10-24 21:18:40,428 [DEBUG] [     rf-engine-0] h.p.r.engine.gear.export.MySQLExporter   > Pushing CSV into MySQL: te_duration_20161024
2016-10-24 21:18:44,942 [DEBUG] [     rf-engine-0] h.p.r.engine.gear.export.MySQLExporter   > Pushing CSV into MySQL: te_address_20161024
2016-10-24 21:18:48,204 [DEBUG] [     rf-engine-0] h.p.r.engine.gear.export.MySQLExporter   > Pushing CSV into MySQL: te_data_20161024
2016-10-24 21:18:49,231 [DEBUG] [     rf-engine-0] h.p.r.engine.gear.export.MySQLExporter   > Pushing CSV into MySQL: te_flag_20161024
2016-10-24 21:18:50,330 [DEBUG] [     rf-engine-0] h.p.r.engine.gear.export.MySQLExporter   > Pushing CSV into MySQL: te_organization_20161024
2016-10-24 21:18:50,785 [ERROR] [     rf-engine-0] h.p.r.engine.boot.RedflagsEngineSession  > Gear finalization failed.
java.sql.SQLException: Incorrect decimal value: '' for column 'rev' at row 4534
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:998) ~[mysql-connector-java-5.1.35.jar!/:5.1.35]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835) ~[mysql-connector-java-5.1.35.jar!/:5.1.35]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771) ~[mysql-connector-java-5.1.35.jar!/:5.1.35]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:870) ~[mysql-connector-java-5.1.35.jar!/:5.1.35]
        at com.mysql.jdbc.MysqlIO.sendFileToServer(MysqlIO.java:3738) ~[mysql-connector-java-5.1.35.jar!/:5.1.35]
        at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:2995) ~[mysql-connector-java-5.1.35.jar!/:5.1.35]
        at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:2245) ~[mysql-connector-java-5.1.35.jar!/:5.1.35]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2638) ~[mysql-connector-java-5.1.35.jar!/:5.1.35]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2531) ~[mysql-connector-java-5.1.35.jar!/:5.1.35]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2489) ~[mysql-connector-java-5.1.35.jar!/:5.1.35]
        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:848) ~[mysql-connector-java-5.1.35.jar!/:5.1.35]
        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:742) ~[mysql-connector-java-5.1.35.jar!/:5.1.35]
        at hu.petabyte.redflags.engine.util.CSV2MySQL.loadCSV(CSV2MySQL.java:105) ~[redflags-engine-1.1.0-SNAPSHOT.jar!/:1.1.0-SNAPSHOT]
        at hu.petabyte.redflags.engine.gear.export.MySQLExporter.afterSession(MySQLExporter.java:115) ~[redflags-engine-1.1.0-SNAPSHOT.jar!/:1.1.0-SNAPSHOT]
        at hu.petabyte.redflags.engine.boot.RedflagsEngineSession.run(RedflagsEngineSession.java:131) ~[redflags-engine-1.1.0-SNAPSHOT.jar!/:1.1.0-SNAPSHOT]
2016-10-24 21:18:50,785 [INFO ] [     rf-engine-0] h.p.r.engine.boot.RedflagsEngineSession  > Finished Redflags engine session with scope hu.petabyte.redflags.engine.epforgpl.EPFScope@4a085fc8 (HEAP: 65M)
2016-10-24 21:18:50,785 [INFO ] [     rf-engine-0] h.p.r.engine.boot.RedflagsEngineSession  > Processed 49000 notices in 4 hours 26 minutes 20 seconds 177 milliseconds
2016-10-24 21:18:50,789 [INFO ] [    main-destroy] h.p.r.engine.boot.RedflagsEngineBoot     > *** REDFLAGS ENGINE - Stopping
```

**Comment by KrzysztofMadejski** [comment]
..

**Comment by dzierzy** [comment]
możesz załączyć wygenerowane przez exportera pliki?

**Comment by KrzysztofMadejski** [comment]
O te chodzi? te_*?

[te_files.zip](https://github.com/petabyte-research/redflags/files/550995/te_files.zip)

**Comment by dzierzy** [comment]
pliki są niestety ucięte więc nie jestem w stanie ich zaimportować. Udało mi się zaimportować 100tyś zamówień (EPFScope ustawiony inicjalnie na stronę 800), import zrealizowany na 8 wątkach, wszystko przebiegło pomyślnie. 
Dla jakich parametrów odbył się u Ciebie import? W logu widzę 49tyś zamówień co daje 98 stron, rozpoczynałeś od strony 902?

**Comment by KrzysztofMadejski** [comment]
Przetwarzam pierwsze sto stron. Wyczyszczę bazę i spróbuję ponownie.

PS. Wiesz może czemu pliki te_ tworzą się w głównym katalogu , a nie w katalogu podanym jako parametr cache?

**Comment by dzierzy** [comment]
udało mi się odtworzyć problem, faktycznie występuje przy przetwarzaniu pierwszych 100 stron. Rozwiążę to w najbliższych dniach.

Ad PS: pliki te tworzą się w katalogu użytkownika który w naszym przypadku jest katalogiem uruchomieniowym. Parametr cache służy do wskazania miejsca przechowania plików pobranych z TED, czyli w naszym przypadku nie jest używany

**Comment by KrzysztofMadejski** [comment]
Dobre wieści :)

**Comment by KrzysztofMadejski** [comment]
Dasz radę w tym tygodniu jeszcze?

**Comment by dzierzy** [comment]
występował problem z importem do bazy w sytuacji gdy w ciągach alfanumerycznych występowały backslash'e. Problem skorygowany poprzez escape'owanie znaków

**Comment by KrzysztofMadejski** [comment]
@juzraai I believe it would be good to merge it back. The best would be to have the standardized CSV export.
